### ISSUE TITLE
Convention for Name, Description, Path "fields"

### ISSUE THREAD

**Issue by DanRathbun** [stevensrmiller/SketchUpFactory#2] opened 2019-09-14 05:38 UTC
#### Name, Description, Path "fields" / properties.

SketchUp API Name and Description properties are empty when first created.
Your factory is stuffing "<_such and such_ unset>" into these "fields".

The initial values are likely null, but the OOP (Ruby API) getters return empty string if the properties are empty/unset because the return type of these getters expect a string. (The API docs tell readers to expect a string.)

Most API path "fields" do the same. Ie, a texture object that has no import path set, or a component definition that was created "on the fly" and not imported will have an empty path.

This convention should be used rather than stuffing something into the property field.

**Comment by stevensrmiller** [comment] 2019-09-14 12:16
For battle-ready production code, that's how it should be. I always include a default string like you see here (one that no one is ever going to use on purpose, and that is self-explanatory) during my testing phases, as it confirms on-sight that the field was initialized as intended (and, if it is missing, that something went wrong).

**Comment by DanRathbun** [comment] 2019-09-14 20:43
Okay, so (playing devel's advocate and a C# novice,) would it be better to use a compiler `#if` block and set the DEBUG symbol ?
```c#
#if DEBUG
    name = "<Name is unset.>";
#else 
    name = "";
#endif
```

**Comment by stevensrmiller** [comment] 2019-09-14 22:21
Yes, that would be better. In fact, Visual Studio defines and undefines the DEBUG directive for you automatically, depending on the build configuration you're using.

Now, I have a life-long aversion to conditional compilaton based on whether I am testing or not. One should test the code that one is going to ship, not some other compilation. So, I tend to use this idiom instead:

```C#
if (isDebugging)
{
    name = "<Name is unset.>";
}
else
{
    name = "";
}
```
This allows you to compile, test, and ship one executable. It also has the advantage that you can ask your customer to run the program in "debug mode," and report any messages. This can be indispensable for that \<SARCASM> oh-so-rare \</SARCASM> case where the customer can reproduce a bug, but you can't.

Either would be an improvement.

**Comment by DanRathbun** [comment] 2019-09-15 01:00
How is `isDebugging` set?

**Comment by stevensrmiller** [comment] 2019-09-15 11:41
I use a command line argument for this. Others prefer a config file setting.

**Comment by DanRathbun** [comment] 2019-09-16 00:10
Concise:
```C#
name = (isDebugging ? "<name is unset>" : "");
```

**Comment by stevensrmiller** [comment] 2019-09-16 01:51
> Concise:
> 
> ```cs
> name = (isDebugging ? "<name is unset>" : "");
> ```

Yes, but also cryptic (and I was trying to parallel the structure of your original version).

At one time, I loved the ternary operator in C. But that was when I believed that line-count was inversely proportional to quality. Today, I value readability over other things. In all likelihood, the compiler would produce the same code with either choice at the source level.

Regardless, this is all a bit general. Let's aim for issues specific to the project. The style choices can be left to our users, no?

**Comment by DanRathbun** [comment] 2019-09-16 03:20
> Regardless, this is all a bit general. Let's aim for issues specific to the project. 

It is specific, as you'd be the one deciding verbose or terse.
It's the OOP Layer that will stuff a debug string in string fields or not.

**You choose since you'll be maintaining it.**
Users would just be "using" the library as is, ie, not likely to be setting `isDebugging`.

I prefer terse as I have arthritis in my hands. The less scrolling the better for me. But that's me.

**Comment by stevensrmiller** [comment] 2019-09-16 11:39
> I have arthritis in my hands. The less scrolling the better for me.

That sucks. I have it in my  knees.

Maybe a couple of these might help you:

<a href=https://www.amazon.com/USB-Foot-Switch-Keyboard-Pedal/dp/B008MU0TBU><img src=https://images-na.ssl-images-amazon.com/images/I/41K1ZUHICBL.jpg></a>

**Comment by stevensrmiller** [comment] 2024-09-05 22:03
Closing this so it doesn't just linger. We can pursue this sort of thing further in Discussions.

**Closed as completed by stevensrmiller** 2024-09-05 22:03 UTC
Labels: peer review
